package rog.domain.enumeration;

public enum SpecifyingCells {
    BIURA, BIURO, URZAD, JEDNOSTKAORGANIZACYJNA, JEDNOSTKAWYKONAWCZA, WYDZIAL,
    WOJEWODZTWO, MIASTO, URZADDZIELNICY, URZEDYDZIELNIC
}
